#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#    May 07, 2024 12:53:26 PM CEST  platform: Linux

#   Rafael Ramírez Salas
#   Ingeniería de Computadores, Universidad de Málaga
#   Trabajo de Fin de Grado 2024: Fail Tolerant DualNano

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import FT_DualNano

_debug = True # False to eliminate debug printing from callback functions.

def main(*args):
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol( 'WM_DELETE_WINDOW' , root.destroy)
    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = root
    _w1 = FT_DualNano.FT_DualNano(_top1)
    root.mainloop()

if __name__ == '__main__':
    FT_DualNano.start_up()


# Path: PAGE/FT_DualNano_support.py