#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 8.0N
#  in conjunction with Tcl version 8.6
#    Dec 10, 2023 08:47:06 AM PST  platform: Linux

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path

_location = os.path.dirname(__file__)

import show_color_support

_bgcolor = 'wheat'  # X11 color: #f5deb3    
_fgcolor = '#000000'  # X11 color: 'black'
_tabfg1 = 'black' 
_tabfg2 = 'black' 
_bgmode = 'light' 
_tabbg1 = '#d9d9d9' 
_tabbg2 = '#b2c9f4' 

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("397x337+733+169")
        top.minsize(1, 1)
        top.maxsize(1905, 1050)
        top.resizable(0,  0)
        top.title("Show Color")
        top.configure(background="wheat")
        top.configure(highlightbackground="wheat")

        self.top = top

        self.Label1 = tk.Label(self.top)
        self.Label1.place(x=30, y=70, height=27, width=151)
        self.Label1.configure(activebackground="#ffffcd")
        self.Label1.configure(background="wheat")
        self.Label1.configure(compound='left')
        self.Label1.configure(disabledforeground="#b8a786")
        self.Label1.configure(font="-family {DejaVu Sans} -size 14 -weight bold")
        self.Label1.configure(highlightbackground="wheat")
        self.Label1.configure(text='''Label''')

        self.Message2 = tk.Message(self.top)
        self.Message2.place(x=60, y=110, height=26, width=89)
        self.Message2.configure(background="wheat")
        self.Message2.configure(cursor="fleur")
        self.Message2.configure(font="-family {DejaVu Sans} -size 13 -weight bold")
        self.Message2.configure(highlightbackground="wheat")
        self.Message2.configure(padx="1")
        self.Message2.configure(pady="1")
        self.Message2.configure(text='''Message''')
        self.Message2.configure(width=90)

        self.Frame1 = tk.Frame(self.top)
        self.Frame1.place(x=40, y=150, height=75, width=125)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="wheat")
        self.Frame1.configure(cursor="fleur")
        self.Frame1.configure(highlightbackground="wheat")

        self.Message2_1 = tk.Message(self.top)
        self.Message2_1.place(x=230, y=110, height=26, width=89)
        self.Message2_1.configure(background="wheat")
        self.Message2_1.configure(cursor="fleur")
        self.Message2_1.configure(font="-family {DejaVu Sans} -size 13 -weight bold")
        self.Message2_1.configure(highlightbackground="wheat")
        self.Message2_1.configure(padx="1")
        self.Message2_1.configure(pady="1")
        self.Message2_1.configure(text='''Message''')
        self.Message2_1.configure(width=90)

        self.Frame1_1 = tk.Frame(self.top)
        self.Frame1_1.place(x=210, y=150, height=75, width=125)
        self.Frame1_1.configure(relief='groove')
        self.Frame1_1.configure(borderwidth="2")
        self.Frame1_1.configure(relief="groove")
        self.Frame1_1.configure(background="wheat")
        self.Frame1_1.configure(cursor="fleur")
        self.Frame1_1.configure(highlightbackground="wheat")

        self.Message3_1 = tk.Message(self.top)
        self.Message3_1.place(x=230, y=230, height=26, width=89)
        self.Message3_1.configure(background="wheat")
        self.Message3_1.configure(cursor="fleur")
        self.Message3_1.configure(font="-family {DejaVu Sans} -size 13 -weight bold")
        self.Message3_1.configure(highlightbackground="wheat")
        self.Message3_1.configure(padx="1")
        self.Message3_1.configure(pady="1")
        self.Message3_1.configure(text='''Message''')
        self.Message3_1.configure(width=90)

        self.Button1 = tk.Button(self.top)
        self.Button1.place(x=160, y=280, height=35, width=69)
        self.Button1.configure(activebackground="beige")
        self.Button1.configure(background="wheat")
        self.Button1.configure(borderwidth="2")
        self.Button1.configure(command=show_color_support.sys.exit)
        self.Button1.configure(compound='left')
        self.Button1.configure(cursor="fleur")
        self.Button1.configure(disabledforeground="#b8a786")
        self.Button1.configure(font="-family {DejaVu Sans} -size 12 -weight bold")
        self.Button1.configure(highlightbackground="wheat")
        self.Button1.configure(text='''Quit''')

        self.Message3 = tk.Message(self.top)
        self.Message3.place(x=60, y=230, height=26, width=89)
        self.Message3.configure(background="wheat")
        self.Message3.configure(cursor="fleur")
        self.Message3.configure(font="-family {DejaVu Sans} -size 13 -weight bold")
        self.Message3.configure(highlightbackground="wheat")
        self.Message3.configure(padx="1")
        self.Message3.configure(pady="1")
        self.Message3.configure(text='''Message''')
        self.Message3.configure(width=90)

        self.Label1_1 = tk.Label(self.top)
        self.Label1_1.place(x=200, y=70, height=27, width=151)
        self.Label1_1.configure(activebackground="#ffffcd")
        self.Label1_1.configure(background="wheat")
        self.Label1_1.configure(compound='left')
        self.Label1_1.configure(cursor="fleur")
        self.Label1_1.configure(disabledforeground="#b8a786")
        self.Label1_1.configure(font="-family {DejaVu Sans} -size 14 -weight bold")
        self.Label1_1.configure(highlightbackground="wheat")
        self.Label1_1.configure(text='''Label''')

        self.Label2 = tk.Label(self.top)
        self.Label2.place(x=77, y=30, height=27, width=59)
        self.Label2.configure(anchor='w')
        self.Label2.configure(background="wheat")
        self.Label2.configure(compound='left')
        self.Label2.configure(disabledforeground="#b8a786")
        self.Label2.configure(font="-family {DejaVu Sans} -size 14 -weight bold")
        self.Label2.configure(text='''Color''')

        self.Label3 = tk.Label(self.top)
        self.Label3.place(x=215, y=30, height=27, width=136)
        self.Label3.configure(anchor='w')
        self.Label3.configure(background="wheat")
        self.Label3.configure(compound='left')
        self.Label3.configure(disabledforeground="#b8a786")
        self.Label3.configure(font="-family {DejaVu Sans} -size 14 -weight bold")
        self.Label3.configure(text='''Complement''')

def start_up():
    show_color_support.main()

if __name__ == '__main__':
    show_color_support.main()




