#############################################################################
# Generated by PAGE version 7.6rc3
#  in conjunction with Tcl version 8.6
#  Nov 29, 2022 03:26:24 AM CST  platform: Linux
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { 
    system_shutdown_png "./images/icons/system-shutdown.png" 
}
vTcl:create_project_images $image_list   ;# In image.tcl

if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) black
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 0
set vTcl(mode) Absolute
}




proc vTclWindow.top44 {base} {
    global vTcl
    if {$base == ""} {
        set base .top44
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background skyblue3 -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 600x450+954+359
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 4225 1410
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "PAGE 7 Treeview Demo"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Main" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    button "$top.but49" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -borderwidth 2 -command "on_btnExit" \
        -compound left \
        -font "-family {DejaVu Sans} -size 10 -weight bold -slant roman -underline 0 -overstrike 0" \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -image system_shutdown_png -text "Exit" 
    vTcl:DefineAlias "$top.but49" "btnExit" vTcl:WidgetProc "Main" 1
    ttk::style configure Treeview \
         -font  "$vTcl(actual_gui_font_treeview_desc)"
    vTcl::widgets::ttk::scrolledtreeview::CreateCmd "$top.scr48" \
        -background $vTcl(actual_gui_bg) -height 431 -highlightcolor black \
        -width 420 
    vTcl:DefineAlias "$top.scr48" "Scrolledtreeview1" vTcl:WidgetProc "Main" 1

        $base.scr48.01 configure -columns Col1 -height 4
        $base.scr48.01 configure -columns {Col1}
        $base.scr48.01 heading #0 -text {Tree}
        $base.scr48.01 heading #0 -anchor center
        $base.scr48.01 column #0 -width 212
        $base.scr48.01 column #0 -minwidth 20
        $base.scr48.01 column #0 -stretch 1
        $base.scr48.01 column #0 -anchor w
        $base.scr48.01 heading Col1 -text {Col1}
        $base.scr48.01 heading Col1 -anchor center
        $base.scr48.01 column Col1 -width 213
        $base.scr48.01 column Col1 -minwidth 20
        $base.scr48.01 column Col1 -stretch 1
        $base.scr48.01 column Col1 -anchor w
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.but49 \
        -in $top -x 460 -y 10 -width 113 -relwidth 0 -height 53 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.scr48 \
        -in $top -x 3 -y 4 -width 439 -relwidth 0 -height 420 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top44 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

