#############################################################################
# Generated by PAGE version 8.0Q
#  in conjunction with Tcl version 8.6
#  Dec 26, 2023 06:15:44 AM CST  platform: Linux
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { 
    chubbyowllogo60_png "./graphics/ChubbyOwlLogo60.png" 
    system_log_out_png "./graphics/system-log-out.png" 
    chubbyowllogo60_png "./graphics/ChubbyOwlLogo60.png" 
}
vTcl:create_project_images $image_list   ;# In image.tcl

set desc "-family {DejaVu Sans} -size 11 -weight bold"
set vTcl(actual_gui_font_dft_desc) $desc
set vTcl(actual_gui_font_dft_name) [font create {*}$desc]
set desc "-family {DejaVu Sans} -size 11 -weight bold"
set vTcl(actual_gui_font_text_desc) $desc
set vTcl(actual_gui_font_text_name) [font create {*}$desc]
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set desc "-family {DejaVu Sans} -size 11 -weight bold"
set vTcl(actual_gui_font_menu_desc) $desc
set vTcl(actual_gui_font_menu_name) [font create {*}$desc]
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) white
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 0
set vTcl(mode) Absolute
set vTcl(project_theme) cornsilk-dark



proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background cornsilk4 -highlightbackground cornsilk4 \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1002x750+746+225
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 4225 1410
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Toplevel 0"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    ttk::label "$top.tLa48" \
        -font "-family {DejaVu Sans} -size 11 -weight bold" -relief flat \
        -anchor center -justify left -image chubbyowllogo60_png \
        -compound none 
    vTcl:DefineAlias "$top.tLa48" "TLabel1" vTcl:WidgetProc "Toplevel1" 1
    ttk::label "$top.tLa49" \
        -font "-family {DejaVu Sans} -size 11 -weight bold" -relief flat \
        -anchor e -justify left -text "Available Themes: " -compound left 
    vTcl:DefineAlias "$top.tLa49" "TLabel2" vTcl:WidgetProc "Toplevel1" 1
    ttk::button "$top.tBu47" \
        -command "on_btnExit" -text "   Exit" -image system_log_out_png \
        -compound left -style "Toolbutton" -style Toolbutton 
    vTcl:DefineAlias "$top.tBu47" "btnExit" vTcl:WidgetProc "Toplevel1" 1
    ttk::checkbutton "$top.tCh47" \
        -variable "tch47" -command "on_ChkApplyBkgnd" \
        -text "Apply Background to Notebook Pages" -compound left 
    vTcl:DefineAlias "$top.tCh47" "chkApplyBkgnd" vTcl:WidgetProc "Toplevel1" 1
    vTcl::widgets::ttk::notebook::createCmd "$top.tNo49" \
        -width 924 -height 524 
    vTcl:DefineAlias "$top.tNo49" "TNotebook1" vTcl:WidgetProc "Toplevel1" 1
    frame "$top.tNo49.t0" \
        -background cornsilk4 -highlightbackground cornsilk4 \
        -highlightcolor black 
    vTcl:DefineAlias "$top.tNo49.t0" "TNotebook1_t1" vTcl:WidgetProc "Toplevel1" 1
    $top.tNo49 add $top.tNo49.t0 \
        -padding 0 -sticky nsew -state normal -text "Page 1" -compound left \
        -underline -1 
    set site_4_0  $top.tNo49.t0
    vTcl::widgets::ttk::scrolledtreeview::CreateCmd "$site_4_0.scr50" \
        -background cornsilk4 -height 15 -width 30 
    vTcl:DefineAlias "$site_4_0.scr50" "Scrolledtreeview1" vTcl:WidgetProc "Toplevel1" 1

        $base.tNo49.t0.scr50.01 configure -columns Col1 -height 4
        $base.tNo49.t0.scr50.01 configure -columns {Col1}
        $base.tNo49.t0.scr50.01 heading #0 -text {Tree}
        $base.tNo49.t0.scr50.01 heading #0 -anchor center
        $base.tNo49.t0.scr50.01 column #0 -width 281
        $base.tNo49.t0.scr50.01 column #0 -minwidth 20
        $base.tNo49.t0.scr50.01 column #0 -stretch 1
        $base.tNo49.t0.scr50.01 column #0 -anchor w
        $base.tNo49.t0.scr50.01 heading Col1 -text {Col1}
        $base.tNo49.t0.scr50.01 heading Col1 -anchor center
        $base.tNo49.t0.scr50.01 column Col1 -width 281
        $base.tNo49.t0.scr50.01 column Col1 -minwidth 20
        $base.tNo49.t0.scr50.01 column Col1 -stretch 1
        $base.tNo49.t0.scr50.01 column Col1 -anchor w
    place $site_4_0.scr50 \
        -in $site_4_0 -x 170 -y 60 -width 580 -relwidth 0 -height 382 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame "$top.tNo49.t1" \
        -background cornsilk4 -highlightbackground cornsilk4 \
        -highlightcolor black 
    vTcl:DefineAlias "$top.tNo49.t1" "TNotebook1_t2" vTcl:WidgetProc "Toplevel1" 1
    $top.tNo49 add $top.tNo49.t1 \
        -padding 0 -sticky nsew -state normal -text "Page 2" -compound left \
        -underline -1 
    set site_4_1  $top.tNo49.t1
    ttk::panedwindow "$site_4_1.tPa51" \
        -orient horizontal 
    vTcl:DefineAlias "$site_4_1.tPa51" "TPanedwindow1" vTcl:WidgetProc "Toplevel1" 1
    ::vTcl::widgets::ttk::labelframe::createCmd "$site_4_1.tPa51.p1" \
        -text "Pane 1" -width 225 -height 200 
    vTcl:DefineAlias "$site_4_1.tPa51.p1" "TPanedwindow1_p1" vTcl:WidgetProc "Toplevel1" 1
    set site_6_0 $site_4_1.tPa51.p1
    vTcl::widgets::ttk::scrolledlistbox::CreateCmd "$site_6_0.scr53" \
        -background cornsilk4 -height 75 -width 125 
    vTcl:DefineAlias "$site_6_0.scr53" "Scrolledlistbox1" vTcl:WidgetProc "Toplevel1" 1

    $site_6_0.scr53.01 configure -background white \
        -cursor xterm \
        -disabledforeground #68665a \
        -exportselection 0 \
        -font TkFixedFont \
        -foreground black \
        -height 3 \
        -highlightbackground cornsilk4 \
        -highlightcolor #d9d9d9 \
        -selectbackground #d9d9d9 \
        -selectforeground black \
        -width 10
    place $site_6_0.scr53 \
        -in $site_6_0 -x 5 -y 40 -width 198 -relwidth 0 -height 391 \
        -relheight 0 -anchor nw -bordermode ignore 
    $site_4_1.tPa51 add $site_4_1.tPa51.p1 
    $site_4_1.tPa51 pane $site_4_1.tPa51.p1 -weight 0
    ::vTcl::widgets::ttk::labelframe::createCmd "$site_4_1.tPa51.p2" \
        -text "Pane 2" -width 125 -height 200 
    vTcl:DefineAlias "$site_4_1.tPa51.p2" "TPanedwindow1_p2" vTcl:WidgetProc "Toplevel1" 1
    set site_6_1 $site_4_1.tPa51.p2
    ttk::panedwindow "$site_6_1.tPa52"
    vTcl:DefineAlias "$site_6_1.tPa52" "TPanedwindow2" vTcl:WidgetProc "Toplevel1" 1
    ::vTcl::widgets::ttk::labelframe::createCmd "$site_6_1.tPa52.p1" \
        -text "Pane 1" -width 200 -height 125 
    vTcl:DefineAlias "$site_6_1.tPa52.p1" "TPanedwindow2_p1" vTcl:WidgetProc "Toplevel1" 1
    set site_8_0 $site_6_1.tPa52.p1
    ttk::radiobutton "$site_8_0.tRa55" \
        -variable "selectedButton" -value "2" -text "TRadio 2" -compound left \
        -style "Toolbutton" -style Toolbutton 
    vTcl:DefineAlias "$site_8_0.tRa55" "TRadiobutton2" vTcl:WidgetProc "Toplevel1" 1
    ttk::radiobutton "$site_8_0.tRa56" \
        -variable "selectedButton" -value "3" -text "TRadio 3" -compound left \
        -style "Toolbutton" -style Toolbutton 
    vTcl:DefineAlias "$site_8_0.tRa56" "TRadiobutton3" vTcl:WidgetProc "Toplevel1" 1
    ttk::radiobutton "$site_8_0.tRa57" \
        -variable "selectedButton" -value "4" -text "TRadio 4" -compound left \
        -style "Toolbutton" -style Toolbutton 
    vTcl:DefineAlias "$site_8_0.tRa57" "TRadiobutton4" vTcl:WidgetProc "Toplevel1" 1
    ttk::radiobutton "$site_8_0.tRa54" \
        -variable "selectedButton" -text "TRadio 1" -compound left \
        -style "Toolbutton" -style Toolbutton 
    vTcl:DefineAlias "$site_8_0.tRa54" "TRadiobutton1" vTcl:WidgetProc "Toplevel1" 1
    place $site_8_0.tRa55 \
        -in $site_8_0 -x 177 -y 48 -width 91 -relwidth 0 -height 28 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_8_0.tRa56 \
        -in $site_8_0 -x 311 -y 48 -width 91 -relwidth 0 -anchor nw \
        -bordermode ignore 
    place $site_8_0.tRa57 \
        -in $site_8_0 -x 445 -y 48 -width 91 -relwidth 0 -anchor nw \
        -bordermode ignore 
    place $site_8_0.tRa54 \
        -in $site_8_0 -x 43 -y 48 -width 91 -relwidth 0 -height 28 \
        -relheight 0 -anchor nw -bordermode ignore 
    $site_6_1.tPa52 add $site_6_1.tPa52.p1 
    $site_6_1.tPa52 pane $site_6_1.tPa52.p1 -weight 0
    ::vTcl::widgets::ttk::labelframe::createCmd "$site_6_1.tPa52.p2" \
        -text "Pane 2" -width 200 -height 125 
    vTcl:DefineAlias "$site_6_1.tPa52.p2" "TPanedwindow2_p2" vTcl:WidgetProc "Toplevel1" 1
    set site_8_1 $site_6_1.tPa52.p2
    ttk::progressbar "$site_8_1.tPr52" \
        -orient vertical -length 100 -mode indeterminate -variable "VProg" 
    vTcl:DefineAlias "$site_8_1.tPr52" "TProgressbar1" vTcl:WidgetProc "Toplevel1" 1
    ttk::progressbar "$site_8_1.tPr53" \
        -length 100 -mode indeterminate -variable "HProg" 
    vTcl:DefineAlias "$site_8_1.tPr53" "TProgressbar2" vTcl:WidgetProc "Toplevel1" 1
    ttk::scale "$site_8_1.tSc50" \
        -variable "VScale" -orient vertical -from 1 -to 100 -value "1" \
        -length 100 
    vTcl:DefineAlias "$site_8_1.tSc50" "TScale1" vTcl:WidgetProc "Toplevel1" 1
    ttk::scale "$site_8_1.tSc51" \
        -variable "HScale" -from 1 -to 100 -value "1" -length 100 
    vTcl:DefineAlias "$site_8_1.tSc51" "TScale2" vTcl:WidgetProc "Toplevel1" 1
    ttk::button "$site_8_1.tBu55" \
        -command "on_btnAnimate" -text "Start Automation" -compound left 
    vTcl:DefineAlias "$site_8_1.tBu55" "btnAnimate" vTcl:WidgetProc "Toplevel1" 1
    ttk::label "$site_8_1.tLa50" \
        -font "-family {DejaVu Sans} -size 11 -weight bold" -relief flat \
        -anchor center -justify left -text "Speed" -compound left 
    vTcl:DefineAlias "$site_8_1.tLa50" "TLabel4" vTcl:WidgetProc "Toplevel1" 1
    ttk::spinbox "$site_8_1.tSp47" \
        -from 20 -to 60 -command "on_Spin" -exportselection 0 \
        -font "-family {DejaVu Sans} -size 11 -weight bold" \
        -textvariable "SpinData" -background white 
    vTcl:DefineAlias "$site_8_1.tSp47" "TSpinbox1" vTcl:WidgetProc "Toplevel1" 1
    place $site_8_1.tPr52 \
        -in $site_8_1 -x 210 -y 50 -anchor nw -bordermode ignore 
    place $site_8_1.tPr53 \
        -in $site_8_1 -x 250 -y 50 -anchor nw -bordermode ignore 
    place $site_8_1.tSc50 \
        -in $site_8_1 -x 30 -y 50 -anchor nw -bordermode ignore 
    place $site_8_1.tSc51 \
        -in $site_8_1 -x 70 -y 50 -anchor nw -bordermode ignore 
    place $site_8_1.tBu55 \
        -in $site_8_1 -x 290 -y 150 -width 222 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_8_1.tLa50 \
        -in $site_8_1 -x 410 -y 60 -width 101 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_8_1.tSp47 \
        -in $site_8_1 -x 420 -y 90 -width 85 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    $site_6_1.tPa52 add $site_6_1.tPa52.p2 
    $site_6_1.tPa52 pane $site_6_1.tPa52.p2 -weight 0
$site_8_0 configure -height 125
    place $site_6_1.tPa52 \
        -in $site_6_1 -x 20 -y 40 -width 580 -relwidth 0 -height 388 \
        -relheight 0 -anchor nw -bordermode ignore 
    $site_4_1.tPa51 add $site_4_1.tPa51.p2 
    $site_4_1.tPa51 pane $site_4_1.tPa51.p2 -weight 0
$site_6_0 configure -width 225
    place $site_4_1.tPa51 \
        -in $site_4_1 -x 20 -y 40 -width 858 -relwidth 0 -height 440 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame "$top.tNo49.t2" \
        -background cornsilk4 -highlightbackground cornsilk4 \
        -highlightcolor black 
    vTcl:DefineAlias "$top.tNo49.t2" "TNotebook1_t3" vTcl:WidgetProc "Toplevel1" 1
    $top.tNo49 add $top.tNo49.t2 \
        -padding 0 -sticky nsew -state normal -text "Page 3" -compound left \
        -underline -1 
    set site_4_2  $top.tNo49.t2
    ttk::frame "$site_4_2.tFr56" \
        -borderwidth 2 -relief groove -width 895 -height 445 
    vTcl:DefineAlias "$site_4_2.tFr56" "TFrame1" vTcl:WidgetProc "Toplevel1" 1
    set site_5_0 $site_4_2.tFr56
    ttk::frame "$site_5_0.tFr57" \
        -borderwidth 2 -relief groove -width 875 -height 425 
    vTcl:DefineAlias "$site_5_0.tFr57" "TFrame2" vTcl:WidgetProc "Toplevel1" 1
    set site_6_0 $site_5_0.tFr57
    ttk::frame "$site_6_0.tFr60" \
        -borderwidth 2 -relief groove -width 185 -height 405 
    vTcl:DefineAlias "$site_6_0.tFr60" "TFrame3" vTcl:WidgetProc "Toplevel1" 1
    set site_7_0 $site_6_0.tFr60
    label "$site_7_0.lab61" \
        -activebackground #d9d9d9 -activeforeground black \
        -background peachpuff2 -compound left -disabledforeground #68665a \
        -font "-family {DejaVu Sans} -size 11 -weight bold" -foreground black \
        -highlightbackground cornsilk4 -highlightcolor black \
        -text "Wrap Settings" 
    vTcl:DefineAlias "$site_7_0.lab61" "Label2" vTcl:WidgetProc "Toplevel1" 1
    ttk::radiobutton "$site_7_0.tRa63" \
        -variable "WrapOption" -value "2" -command "on_WrapSettings" \
        -text "Char" -compound left -style "Toolbutton" -style Toolbutton 
    vTcl:DefineAlias "$site_7_0.tRa63" "TRadiobutton6" vTcl:WidgetProc "Toplevel1" 1
    ttk::radiobutton "$site_7_0.tRa64" \
        -variable "WrapOption" -value "3" -command "on_WrapSettings" \
        -text "Word" -compound left -style "Toolbutton" -style Toolbutton 
    vTcl:DefineAlias "$site_7_0.tRa64" "TRadiobutton7" vTcl:WidgetProc "Toplevel1" 1
    ttk::radiobutton "$site_7_0.tRa62" \
        -variable "WrapOption" -command "on_WrapSettings" -text "None" \
        -compound left -style "Toolbutton" -style Toolbutton 
    vTcl:DefineAlias "$site_7_0.tRa62" "TRadiobutton5" vTcl:WidgetProc "Toplevel1" 1
    place $site_7_0.lab61 \
        -in $site_7_0 -x 10 -y 10 -width 164 -relwidth 0 -height 32 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_7_0.tRa63 \
        -in $site_7_0 -x 25 -y 100 -width 130 -relwidth 0 -height 32 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_7_0.tRa64 \
        -in $site_7_0 -x 25 -y 140 -width 130 -relwidth 0 -height 32 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_7_0.tRa62 \
        -in $site_7_0 -x 25 -y 60 -width 130 -relwidth 0 -height 32 \
        -relheight 0 -anchor nw -bordermode ignore 
    label "$site_6_0.lab59" \
        -activebackground #d9d9d9 -activeforeground black \
        -background peachpuff2 -borderwidth 2 -compound left \
        -disabledforeground #68665a \
        -font "-family {DejaVu Sans} -size 11 -weight bold" -foreground black \
        -highlightbackground cornsilk4 -highlightcolor black -relief groove \
        -text "ScrolledText widget" 
    vTcl:DefineAlias "$site_6_0.lab59" "Label1" vTcl:WidgetProc "Toplevel1" 1
    vTcl::widgets::ttk::scrolledtext::CreateCmd "$site_6_0.scr58" \
        -borderwidth 2 -relief groove -background cornsilk4 -height 75 \
        -width 125 
    vTcl:DefineAlias "$site_6_0.scr58" "Scrolledtext1" vTcl:WidgetProc "Toplevel1" 1

    $site_6_0.scr58.01 configure -background white \
        -exportselection 0 \
        -font "-family {DejaVu Sans} -size 11 -weight bold" \
        -foreground black \
        -height 3 \
        -highlightbackground cornsilk4 \
        -highlightcolor black \
        -insertbackground black \
        -insertborderwidth 3 \
        -selectbackground #d9d9d9 \
        -selectforeground black \
        -width 10 \
        -wrap none
    place $site_6_0.tFr60 \
        -in $site_6_0 -x 690 -y 3 -width 185 -relwidth 0 -height 405 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_6_0.lab59 \
        -in $site_6_0 -x 10 -y 10 -width 674 -relwidth 0 -height 32 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_6_0.scr58 \
        -in $site_6_0 -x 10 -y 50 -width 674 -relwidth 0 -height 370 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.tFr57 \
        -in $site_5_0 -x 10 -y 10 -width 875 -relwidth 0 -height 425 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.tFr56 \
        -in $site_4_2 -x 20 -y 20 -width 895 -relwidth 0 -height 445 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame "$top.tNo49.t3" \
        -background cornsilk4 -highlightbackground cornsilk4 \
        -highlightcolor black 
    vTcl:DefineAlias "$top.tNo49.t3" "TNotebook1_t4" vTcl:WidgetProc "Toplevel1" 1
    $top.tNo49 add $top.tNo49.t3 \
        -padding 0 -sticky nsew -state normal -text "Page 4" -compound left \
        -underline -1 
    set site_4_3  $top.tNo49.t3
    ttk::label "$site_4_3.tLa50" \
        -font "-family {DejaVu Sans} -size 11 -weight bold" -relief flat \
        -anchor w -justify left -image chubbyowllogo60_png -compound none 
    vTcl:DefineAlias "$site_4_3.tLa50" "TLabel5" vTcl:WidgetProc "Toplevel1" 1
    ttk::separator "$site_4_3.tSe48"
    vTcl:DefineAlias "$site_4_3.tSe48" "TSeparator1" vTcl:WidgetProc "Toplevel1" 1
    ttk::label "$site_4_3.tLa47" \
        -font "-family {DejaVu Sans} -size 16 -weight bold -slant italic" \
        -relief flat -anchor center -justify left -text "ABOUT" \
        -compound left 
    vTcl:DefineAlias "$site_4_3.tLa47" "TLabel3" vTcl:WidgetProc "Toplevel1" 1
    message "$site_4_3.mes49" \
        -anchor n -background cornsilk4 -borderwidth 3 \
        -font "-family {DejaVu Sans} -size 14 -weight bold" -foreground black \
        -highlightbackground cornsilk4 -highlightcolor black -justify center \
        -padx 1 -pady 1 -relief ridge \
        -text "


This program was written by Gregory Walters.

Copyright © 2023, 2024 by Gregory Walters

This program is licensed under the MIT license (see license.txt)

" \
        -width 885 
    vTcl:DefineAlias "$site_4_3.mes49" "Message1" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_3.tLa50 \
        -in $site_4_3 -x 20 -y 20 -anchor nw -bordermode ignore 
    place $site_4_3.tSe48 \
        -in $site_4_3 -x 120 -y 71 -width 780 -relwidth 0 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $site_4_3.tLa47 \
        -in $site_4_3 -x 349 -y 16 -width 221 -relwidth 0 -height 44 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_3.mes49 \
        -in $site_4_3 -x 20 -y 100 -width 885 -relwidth 0 -height 364 \
        -relheight 0 -anchor nw -bordermode ignore 
    vTcl:copy_lock $top.tNo49
    ttk::combobox "$top.tCo47" \
        -exportselection 0 -font "-family {DejaVu Sans} -size 10" \
        -textvariable "comboThemes" 
    vTcl:DefineAlias "$top.tCo47" "TComboThemes" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tLa48 \
        -in $top -x 10 -y 10 -width 70 -relwidth 0 -height 70 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tLa49 \
        -in $top -x 130 -y 31 -width 201 -relwidth 0 -height 24 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tBu47 \
        -in $top -x 840 -y 20 -anchor nw -bordermode ignore 
    place $top.tCh47 \
        -in $top -x 150 -y 70 -width 415 -relwidth 0 -height 36 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tNo49 \
        -in $top -x 30 -y 130 -width 924 -relwidth 0 -height 524 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tCo47 \
        -in $top -x 336 -y 32 -width 200 -relwidth 0 -height 24 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

